[package]
name = "stack-control"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
unicode-segmentation = "1.10.1"
indoc = "2"
strum = "0.27"
strum_macros = "0.27"
thiserror = "2.0.12"
